INSERT INTO CARDAPIO VALUES('Alho e Óleo', 'Molho, mussarela, alho e óleo, orégano', 20);
INSERT INTO CARDAPIO VALUES('Alicci', 'Molho, mussarela, alicci e orégano', 20);
INSERT INTO CARDAPIO VALUES('Americana', 'molho, mussarela, bacon, milho, ovos e orégano', 21);
INSERT INTO CARDAPIO VALUES('Atum', 'Molho, mussarela, atum e orégano', 22);
INSERT INTO CARDAPIO VALUES('Bacon', 'Molho, mussarela, bacon e orégano', 21);
INSERT INTO CARDAPIO VALUES('Baiana', 'Molho, mussarela, calabresa, pimenta e orégano', 25);
INSERT INTO CARDAPIO VALUES('Bolonhesa', 'Molho, mussarela, carne moída e orégano', 25);
INSERT INTO CARDAPIO VALUES('Brasileira', 'Molho, mussarela, milho, ervilha e orégano', 20);
INSERT INTO CARDAPIO VALUES('Brócolis', 'Molho, mussarela, brócolis, bacon, catupiry e orégano', 21);
INSERT INTO CARDAPIO VALUES('Calabresa', 'Molho, mussarela, calabresa e orégano', 22);
INSERT INTO CARDAPIO VALUES('Calabresa com Catupiry', 'Molho, mussarela, calabresa, catupiry e orégano', 23);
INSERT INTO CARDAPIO VALUES('Calabresa com Cheddar', 'Molho, mussarela, calabresa, cheddar e orégano', 23);
INSERT INTO CARDAPIO VALUES('Calabresa Mineira', 'Molho, mussarela, calabresa, milho, bacon e orégano', 23);
INSERT INTO CARDAPIO VALUES('Camponesa', 'Molho, mussarela, frango, tomate picado, gorgonzola e manjericão', 22);
INSERT INTO CARDAPIO VALUES('Catupiry', 'Molho, mussarela, catupiry e orégano', 21);
INSERT INTO CARDAPIO VALUES('Champignon', 'Molho, mussarela, champignon e orégano', 25);
INSERT INTO CARDAPIO VALUES('Crocante', 'Molho, mussarela, presunto, bacon, milho, batata palha e orégano', 24);
INSERT INTO CARDAPIO VALUES('Escarola', 'Molho, mussarela, escarola, alho, bacon e orégano', 23);
INSERT INTO CARDAPIO VALUES('Frango', 'Molho, mussarela, frango e orégano', 21);
INSERT INTO CARDAPIO VALUES('Frango Caipira', 'Molho, mussarela, frango, catupiry, bacon, milho e orégano', 22);
INSERT INTO CARDAPIO VALUES('Frango com Catupiry', 'Molho, mussarela, frango, catupiry e orégano', 22);
INSERT INTO CARDAPIO VALUES('Frango com Cheddar', 'Molho, mussarela, frango, cheddar e orégano', 22);
INSERT INTO CARDAPIO VALUES('Gorgonzola', 'Molho, mussarela, tomate, gorgonzola e orégano', 26);
INSERT INTO CARDAPIO VALUES('Grega', 'Molho, mussarela, lombo, cebola, palmito e orégano', 23);
INSERT INTO CARDAPIO VALUES('Havaiana', 'Molho, mussarela, lombo e abacaxi', 23);
INSERT INTO CARDAPIO VALUES('Humita', 'Molho, mussarela, presunto, milho e orégano', 22);
INSERT INTO CARDAPIO VALUES('Lombo', 'Molho, mussarela, lombo e orégano', 22);
INSERT INTO CARDAPIO VALUES('Lombo Califórnia', 'Molho, mussarela, lombo, califórnia e orégano', 23);
INSERT INTO CARDAPIO VALUES('Lombo Canadense', 'Molho, mussarela, lombo, tomate, alicci, parmesão e orégano', 26);
INSERT INTO CARDAPIO VALUES('Lombo com Catupiry', 'Molho, mussarela, lombo, catupiry e orégano', 24);
INSERT INTO CARDAPIO VALUES('Lombo com Champignon', 'Molho, mussarela, lombo, champignon e orégano', 24);
INSERT INTO CARDAPIO VALUES('Lombo com Cheddar', 'Molho, mussarela, lombo, cheddar e orégano', 24);
INSERT INTO CARDAPIO VALUES('Lombo Especial', 'Molho, mussarela, lombo, champignon, catupiry e orégano', 27);
INSERT INTO CARDAPIO VALUES('Maguerita', 'Molho, mussarela, tomate e manjericão', 28);
INSERT INTO CARDAPIO VALUES('Maiale', 'Molho, mussarela, lombo, calabresa, bacon e orégano', 22);
INSERT INTO CARDAPIO VALUES('Marinara', 'Molho, mussarela, atum, tomate picado, provolone e orégano', 23);
INSERT INTO CARDAPIO VALUES('Mexicana', 'Molho, mussarela, calabresa, cebola, pimenta e orégano', 22);
INSERT INTO CARDAPIO VALUES('Milho Verde', 'Molho, mussarela, milho verde e orégano', 23);
INSERT INTO CARDAPIO VALUES('Mussarela', 'Molho, mussarela e orégano', 27);
INSERT INTO CARDAPIO VALUES('Napolitana', 'Molho, mussarela, tomate, parmesão e orégano', 20);
INSERT INTO CARDAPIO VALUES('Palmito', 'Molho, mussarela, palmito e orégano', 21);
INSERT INTO CARDAPIO VALUES('Palmito Especial', 'Molho, mussarela, palmito, milho, bacon e orégano', 23);
INSERT INTO CARDAPIO VALUES('Parmegiana', 'Mussarela, molho ao sugo, parmesão e orégano', 25);
INSERT INTO CARDAPIO VALUES('Paulista', 'Molho, mussarela, palmito, ervilha e orégano', 23);
INSERT INTO CARDAPIO VALUES('Peruana', 'Massa, molho, mussarela, atum, cebola, ervilha e orégano', 23);
INSERT INTO CARDAPIO VALUES('Portuguesa', 'Molho, mussarela, presunto, cebola, ovos, azeitona e orégano', 26);
INSERT INTO CARDAPIO VALUES('Provolone', 'Molho, mussarela, provolone e orégano', 25);
INSERT INTO CARDAPIO VALUES('QDelícia', 'Molho, mussarela, bolonhesa, cebola, batata palha e orégano', 27);
INSERT INTO CARDAPIO VALUES('Quatro Queijos', 'Molho, mussarela, provolone, parmesão, catupiry e orégano', 29);
INSERT INTO CARDAPIO VALUES('Romana', 'Molho, mussarela, presunto e orégano', 23);
INSERT INTO CARDAPIO VALUES('Siciliana', 'Molho, mussarela, champignon, bacon, pimentão, azeitona e orégano', 20);
INSERT INTO CARDAPIO VALUES('Vegetariana', 'Molho, mussarela, escarola, tomate, milho, ervilha e orégano', 24);